### ISSUE TITLE
Tools page sending people to broken URL

### ISSUE THREAD

**Issue by cshurtz** [lifechurch/lifechurch-site#624]
Problem: In the Tools page, the link to the app page is going to the wrong URL. 

http://www.life.church/tools/?utm_source=life.church&utm_medium=website&utm_content=MoreMenu-Tools&utm_campaign=Life.Church

It's going to http://www.life.church/apps/ but it should be http://www.life.church/app

**Comment by danielrwoodward** [comment]
@benhaan - we should set up a redirect from /apps to /app - its a pretty common error

**Comment by benhaan** [comment]
@cshurtz @danielrwoodward this is now fixed.
